### ISSUE TITLE
我们老师想让我做一个斗地主的托管程序，请问可以吗，谢谢

### ISSUE THREAD

**Issue by Devil13ele** [qq456cvb/doudizhu-C#10]
我想用这个训练一个自动打牌的ai可以吗

**Comment by qq456cvb** [comment]
非商业用途随便用

**Comment by Devil13ele** [comment]
谢谢，不是商业用途的，但我是个萌新，make那步出错了
/home/que/projects/doudizhu-C-master/main.cpp:1098:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(env, m) {
                ^
CMakeFiles/env.dir/build.make:62: recipe for target 'CMakeFiles/env.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/env.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/env.dir/all' failed
make[1]: *** [CMakeFiles/env.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qq456cvb** [comment]
你安装pybind11了吗 https://pybind11.readthedocs.io/

**Comment by Devil13ele** [comment]
安了

**Comment by Devil13ele** [comment]
不好意思，应该是这堆
/home/que/projects/doudizhu-C-master/main.cpp:204:26: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
         auto c = pycards.unchecked<1>();
                          ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:204:39: error: expected primary-expression before ‘)’ token
         auto c = pycards.unchecked<1>();
                                       ^
/home/que/projects/doudizhu-C-master/main.cpp: In member function ‘std::tuple<int, bool> Env::step2(pybind11::array_t<int>)’:
/home/que/projects/doudizhu-C-master/main.cpp:294:34: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
                 auto arr = cards.unchecked<1>();
                                  ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:294:47: error: expected primary-expression before ‘)’ token
                 auto arr = cards.unchecked<1>();
                                               ^
/home/que/projects/doudizhu-C-master/main.cpp: In member function ‘auto Env::step(bool, pybind11::array_t<int>)’:
/home/que/projects/doudizhu-C-master/main.cpp:803:34: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
                 auto arr = cards.unchecked<1>();
                                  ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:803:47: error: expected primary-expression before ‘)’ token
                 auto arr = cards.unchecked<1>();
                                               ^
/home/que/projects/doudizhu-C-master/main.cpp: In member function ‘auto Env::step_manual(pybind11::array_t<int>, int)’:
/home/que/projects/doudizhu-C-master/main.cpp:892:30: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
             auto arr = cards.unchecked<1>();
                              ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:892:43: error: expected primary-expression before ‘)’ token
             auto arr = cards.unchecked<1>();
                                           ^
/home/que/projects/doudizhu-C-master/main.cpp: In member function ‘auto Env::will_lose_control(pybind11::array_t<int>)’:
/home/que/projects/doudizhu-C-master/main.cpp:982:24: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
         auto c = cards.unchecked<1>();
                        ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:982:37: error: expected primary-expression before ‘)’ token
         auto c = cards.unchecked<1>();
                                     ^
/home/que/projects/doudizhu-C-master/main.cpp: In static member function ‘static auto Env::step_auto_static(pybind11::array_t<int>, pybind11::array_t<int>)’:
/home/que/projects/doudizhu-C-master/main.cpp:1016:28: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
         auto c = handcards.unchecked<1>();
                            ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:1016:41: error: expected primary-expression before ‘)’ token
         auto c = handcards.unchecked<1>();
                                         ^
/home/que/projects/doudizhu-C-master/main.cpp:1029:46: error: ‘class pybind11::array_t<int>’ has no member named ‘unchecked’; did you mean ‘_check’?
             auto last_cards_ptr = last_cards.unchecked<1>();
                                              ^~~~~~~~~
/home/que/projects/doudizhu-C-master/main.cpp:1029:59: error: expected primary-expression before ‘)’ token
             auto last_cards_ptr = last_cards.unchecked<1>();
                                                           ^
/home/que/projects/doudizhu-C-master/main.cpp: At global scope:
/home/que/projects/doudizhu-C-master/main.cpp:1098:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(env, m) {
                ^
CMakeFiles/env.dir/build.make:62: recipe for target 'CMakeFiles/env.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/env.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/env.dir/all' failed
make[1]: *** [CMakeFiles/env.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Devil13ele** [comment]
是不是版本的兼容问题

**Comment by qq456cvb** [comment]
应该和pybind11版本无关，最新的版本有这个方法 https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#direct-access，你可以看看是否用C++11编译，以及pybind11是否安装正确

**Comment by qq456cvb** [comment]
已更新tutorial，如有问题再开issue
