### ISSUE TITLE
Release of DouZero DouDizhu AI

### ISSUE THREAD

**Issue by daochenzha** [qq456cvb/doudizhu-C#17]
Hi authors,

First of all, thanks very much for the project. I have studied your project and your paper very carefully, which are very helpful in my research.

I just want to share that we have recently released DouZero, a simple yet strong DouDizhu AI. We have also included your algorithm and RHCP as baselines. I noticed that this project is not actively maintained in the last few years. Actually, we are actively maintaining a toolkit and an open-sourced project, and we will keep doing so in the future. I wonder if it is possible to add some links to the README of your project to point to our project so that users interested in DouDizhu can see our projects as well. Our projects links are as follows:

RLCard: https://rlcard.org/
DouZero: https://github.com/kwai/DouZero
Paper: https://arxiv.org/abs/2106.06135
Online Demo: https://douzero.org/

Looking forward to hearing from you!

**Comment by qq456cvb** [comment]
Sure, your work on DouZero is really exciting. We've added some introduction of your algorithm in README.

**Comment by initial-h** [comment]
@daochenzha @qq456cvb 请问如何接到douzero里进行比较呢，我看douzero目前没有开源您提到的 ‘We have also included your algorithm and RHCP as baselines.’ 谢谢。
