### ISSUE TITLE
Does RHCP consider the position 

### ISSUE THREAD

**Issue by chiangqiqi** [qq456cvb/doudizhu-C#2]
Hi, 

```
class RHCPAgent(Agent):
    def intention(self, env):
        intention = to_char(CEnv.step_auto_static(Card.char2color(env.get_curr_handcards()), to_value(env.get_last_outcards())))
        return intention
```
check out the code and find that this RHCP agent does not take an input of it's position.

Is this means that RHCP just only consider the cards in its hand but do not consider its position?

**Comment by qq456cvb** [comment]
No, currently RHCP is unaware of its position.
