### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by windar427** [qq456cvb/doudizhu-C#5]
```
from env import Env as CEnv
```
can't find env.py

**Comment by qq456cvb** [comment]
You should compile the source code (main.cpp) with CMakeLists.txt. I am using Pybind11 to communicate between C++ and Python.

**Comment by Tcloser** [comment]
> ```
> from env import Env as CEnv
> ```
> 
> can't find env.py

请问解决了吗？
我的一直是这个问题。。。
`from env import Env as CEnv
ImportError: generic_type: type "Env" is already registered!`

**Comment by Tcloser** [comment]
##### ImportError: generic_type: type "Env" is already registered! 
Go to doudizhu/doudizhu-C/CMakeLists.txt change 
`pybind11_add_module(env main.cpp card.hpp card.cpp game.cpp game.hpp dancing_link.cpp) 
if(MSVC`
to `pybind11_add_module(main.cpp card.hpp card.cpp game.cpp game.hpp dancing_link.cpp) 
if(MSVC`

##### can't find env.py
`pip install env`
