### ISSUE TITLE
Memory overflow（内存溢出）

### ISSUE THREAD

**Issue by loserZhang** [qq456cvb/doudizhu-C#7]
您好，在我运行您代码时，发现我gpu显存会一直往上增加，请问这是不是内存溢出了，同时测试的时候load模型参数是模型的路径吗？

**Comment by sunnyForIOS** [comment]
@loserZhang 你训练的模型效果怎么样

**Comment by sunnyForIOS** [comment]
@loserZhang 276749553 QQ交流 我正在做斗地主AI
