### ISSUE TITLE
how to use pretrained model?

### ISSUE THREAD

**Issue by sunnyForIOS** [qq456cvb/doudizhu-C#9]
pred = OfflinePredictor(PredictConfig(
            model=Model(),
            session_init=get_model_loader(args.load),
            input_names=['state', 'comb_mask'],
            output_names=['Qvalue']))

 **input_names** should be ['state', 'comb_mask', '**fine_mask**'],  can you show me a example about use the Predictor

**Comment by qq456cvb** [comment]
The source code to reproduce the multi-agent hierarchical algorithm in the paper is under `TensorPack/MA_Hierarchical_Q`, where we wrap the predictor in `predictor.py`. `baseline_evaluator.py` will call `predictor.py` and then evaluate the result against baseline algorithms.

**Comment by sunnyForIOS** [comment]
can you give me a trained model with MA_Hierarchical_Q, i try to train it but it is very slow and the gpu is bomb after few minutes.

**Comment by qq456cvb** [comment]
I've updated the tutorial and the pretrained model.
